### ISSUE TITLE
Config option to disable Prometheus from generating.

### ISSUE THREAD

**Issue by Mobanicman** [Ri5ux/AliensVsPredator#1]
We are currently having problems within our server with Prometheus its generating but its using all vanilla id's and spawning in dragon eggs in place of hugger eggs. The ship is also made out of nether brick and clay blocks. I was just wondering if you would be able to add a disabling feature within the config file.

**Comment by hsyyid** [comment]
Please specify the build number of AIRI, AvP, etc.

**Comment by Mobanicman** [comment]
Latest of both

**Comment by Mobanicman** [comment]
but for numbers sake AIRI [1.7.10-10.13.4.1492-1.7.10][3.1.0.161]    AVP [1.7.10-10.13.4.1492-1.7.10][4.0.0.275]

**Comment by Ri5ux** [comment]
You're running a beta build. The ship was currently implemented in that way. There's nothing actually wrong with it, just unfinished. The ship will only generate 3 times per world, so there shouldnt be much of a problem. A config option can be added though and may be in the future.
