### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by NobleSaurusRex** [Ri5ux/AliensVsPredator#10]
Love the mod! But could you please add some better moving AI for the mobs? also, Could you please add a better AI for the xenomorph drones when building their hive?

**Comment by Njet75** [comment]
They should also be able to fit in 1 block height.

**Comment by bvanseg** [comment]
All of the entities in the game have been fitted with a new AI system as of the most recent builds. "better moving" AI and "better" AI for hive building are pretty vague. Unless the original issue poster clarifies what they mean by better or can suggest specific improvements for the AI, I'm considering this issue closed.
