### ISSUE TITLE
Ceiling fan, grill blocks have "Xray effect" when placed

### ISSUE THREAD

**Issue by darthvader45** [Ri5ux/AliensVsPredator#10]
Seems these blocks have an xray effect when placed down.  I'd recommend making them act like glass, code-wise.  This would alleviate the effect.

![image](https://cloud.githubusercontent.com/assets/2816420/19620647/f726337a-984f-11e6-9ad2-a3323e5178cc.png)

**Comment by Ri5ux** [comment]
This is now resolved.
