### ISSUE TITLE
Crash latest AVP  aliensvspredator-7.0.0.68 + mdxlib-4.0.0.35

### ISSUE THREAD

**Issue by Njet75** [Ri5ux/AliensVsPredator#129]
Get this crash in my modpack  AVP  aliensvspredator-7.0.0.68 + mdxlib-4.0.0.35.
See attached crashreport.
[crash-2023-03-18_12.04.19-client.txt](https://github.com/Ri5ux/AliensVsPredator/files/11008319/crash-2023-03-18_12.04.19-client.txt)

**Comment by bvanseg** [comment]
This is a known issue. A fix is expected in the next release!
