### ISSUE TITLE
Xenomorph Queen & Hive Mechanics Broken

### ISSUE THREAD

**Issue by GarchompGirl** [Ri5ux/AliensVsPredator#13]
Ok so the Xenomorph Queen in the 1.7.10, 1.10.2, and 1.12.2 versions of the AVP mod is basically broken. The 1.7.10 version of AVP when you spawn a Queen she just doesn't move around. Plus her egg-sac grows a tiny bit after every day tick plus she grows it without any hive resin whatsoever. She lays Ovamorphs very slowly like every one and a half minutes instead of every second when her egg-sac is fully grown. When you place her down she instantly starts growing her egg-sac and it grows like what I said in the 3rd sentence. Drones spread hive resin but the other types of Xenomorphs don't. (Runner, Etc,) I once used one of those Stasis Mechanism on a Queen and instead of laying 1 Ovamorph it was 3 Ovamorphs.

For 1.12.2/1.10.2: The Queen when you spawn one in 1.12.2 moves around for about 5 seconds then just stops moving and grows the egg-sac slowly like the 1.7.10 one, but there is a glitch that it made the Queen grow a egg-sac very fast:

Here is the steps of reproducing this glitch.
 1: Launch 1.12.2 Forge with the AVP mod in mods folder plus MDX Lib

 2: Create a new world that has cheats allowed and set the gamemode to Creative for it

 3: Do /gamerule doDaylightCycle false 

 4: Then /time set day

 5: Spawn a Xenomorph Queen

The Queen grows the egg-sac quickly but doesn't lay any Ovamorphs, Drones did not place hive resin, and Xenomorphs did not eat any royal jelly. In 1.7.10 when I did /gamerule doDaylightCycle false the other Queens that were already there stopped growing their egg-sacs. The Queens that I spawned in after doing that command were aggressive like a normal Xenomorph. The Drones did not place any hive resin even though they killed all the pigs around them.
Here is some images I got. (Their in the 1.12.2 Version of AVP that had the Updated Deacon, Belugamorphs and had the Sporepod)
![image](https://user-images.githubusercontent.com/40581633/51796594-b7e6ef00-21ab-11e9-9e50-8b5f77664885.png)
![image](https://user-images.githubusercontent.com/40581633/51796729-6f7c0100-21ac-11e9-8c79-2b003bbc9d1f.png)
Also when I did /time add 1000000000 and spammed it the Queens egg-sac magically disappeared
![image](https://user-images.githubusercontent.com/40581633/51796772-12347f80-21ad-11e9-88a7-c4e7b1ed29c6.png)

**Comment by bvanseg** [comment]
These issues were not reproducible in a dev nor a production environment on my end.

Despite that, PR #26 should resolve most of the issues you brought up @GarchompGirl. 👍

**Comment by SashaIndustries** [comment]
Unsure if its a mod conflict but I also experience this issue. The drones are not digging on 1.12.2 for me ether
