### ISSUE TITLE
Xenomorphs not attacking

### ISSUE THREAD

**Issue by SirXen0** [Ri5ux/AliensVsPredator#14]
Overworld spawning Xenomorph Drones/Warriors are not attacking anything and just stand still, no wandering.
Does not aggro onto any mob/player in survival mode. 
ver 4.0.0.625

**Comment by Xorgadget** [comment]
Can you send a gif, picture or video for reference?

**Comment by Xorgadget** [comment]
[this should be fixed now.](https://github.com/Ri5ux/AliensVsPredator/commit/172d6779d65fd4a55ee6cd13d2a75176cf770702)

**Comment by Xorgadget** [comment]
![image](https://cloud.githubusercontent.com/assets/20858676/19764709/d2771a8c-9c44-11e6-9287-a7372446a098.png)
They do not attack but they do excel at making hisses.

**Comment by SirXen0** [comment]
I'll do a shadowplay of what happens, give me about 30 mins (was at work, sorry for long reply)

**Comment by SirXen0** [comment]
Video with timestamps in description: https://youtu.be/sBX8zdPzDkc
Also from looking at the code, I think I know what the issue is (I don't have any java programming but I know C).

In [this commit](https://github.com/Ri5ux/AliensVsPredator/commit/172d6779d65fd4a55ee6cd13d2a75176cf770702), I'm not sure what tasks.addtask derives from so I'm just going on a hunch.
`    protected void addStandardXenomorphAISet()
    {
        this.tasks.addTask(0, new EntityAISwimming(this));
        this.tasks.addTask(2, new EntityAIAttackOnCollide(this, EntityCreature.class, 1.0D, false));
        this.tasks.addTask(2, new EntityAIWatchClosest(this, EntityLivingBase.class, 16F));
        this.tasks.addTask(2, new EntityAIWander(this, 0.8D));
        this.tasks.addTask(3, new EntityAILeapAtTarget(this, 0.6F));
        this.targetTasks.addTask(0, new EntityAIHurtByTarget(this, true));
        this.targetTasks.addTask(1, new EntityAINearestAttackableTarget(this, EntityCreature.class, 0, false, false, EntitySelectorXenomorph.instance));
    }`

Shouldn't this be:

`    protected void addStandardXenomorphAISet()
    {
        this.tasks.addTask(0, new EntityAISwimming(this));
        this.tasks.addTask(1, new EntityAIAttackOnCollide(this, EntityCreature.class, 1.0D, false));
        this.tasks.addTask(2, new EntityAIWatchClosest(this, EntityLivingBase.class, 16F));
        this.tasks.addTask(3, new EntityAIWander(this, 0.8D));
        this.tasks.addTask(4, new EntityAILeapAtTarget(this, 0.6F));
        this.targetTasks.addTask(0, new EntityAIHurtByTarget(this, true));
        this.targetTasks.addTask(1, new EntityAINearestAttackableTarget(this, EntityCreature.class, 0, false, false, EntitySelectorXenomorph.instance));
    }`

I don't know your code but that's what I'd think is wrong, but I don't know what it derives from what the numbers are (guessing task list? or priority?) and is skipping the tasks below EntityAISwimming because the next task in the list doesn't exist.
Hope the vid helps.

**Comment by SirXen0** [comment]
Also I realised that 
`this.tasks.addTask(1, new EntityAIAttackOnCollide(this, EntityPlayer.class, 0.8D, true));`
got removed in the latest commit so that's probably to blame (since there's no task for the xenomorph to attack the player) as well.

**Comment by SirXen0** [comment]
Latest update causes Xenomorphs to attack almost never. (I've only managed to get a Queen to fight back).

**Comment by Ri5ux** [comment]
This issue has been resolved as of last night. Xenomorphs should attack as expected, I tested it personally. Please submit a new issue if you find that it continues to be unresolved.
