### ISSUE TITLE
#NOTE the main site is down.

### ISSUE THREAD

**Issue by Xorgadget** [Ri5ux/AliensVsPredator#15]
[https://aliensvspredator.org/page/download/index.php](https://aliensvspredator.org/page/download/index.php)

**Comment by Xorgadget** [comment]
It seemed to be the DNS address. I shall find out any other information if it happens again.

**Comment by Ri5ux** [comment]
It was due to SSL being removed from the website. I tried to remove the SSL based links (HTTPS) from as many places as I could. If you find any others, please let me know.
