### ISSUE TITLE
Crashing Sever (1.7.10) 

### ISSUE THREAD

**Issue by LuciferWPF** [Ri5ux/AliensVsPredator#15]
Im recieving this error which is followed by the crash of my server, i would appreciate any help as i cannot seem to be able to fix this myself...

> java.lang.IllegalArgumentException: No enum constant
> org.bukkit.block.Biome.LV-223.B.1 (Varda Badlands)
> Time: 4/1/19 6:16 PM
> Description: Exception in server tick loop
>
> java.lang.IllegalArgumentException: No enum constant
> org.bukkit.block.Biome.LV-223.B.1 (Varda Badlands)
> at java.lang.Enum.valueOf(Enum.java:238)
> at
>
> org.bukkit.craftbukkit.v1_7_R4.block.CraftBlock.initMappings(CraftBlock.java:578)
> at
>
> org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:337)
> at
>
> net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)
> at
>
> net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:174)
> at net.minecraft.world.World. (World.java:349)
> at net.minecraft.world.WorldServer. (WorldServer.java:153)
> at
>
> net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356)

**Comment by BRAINS-OF-FURY** [comment]
kden

**Comment by bvanseg** [comment]
The mod is no longer supported for MC version 1.7.10. Please consider updating.
