### ISSUE TITLE
AVP recipes not using oredict?

### ISSUE THREAD

**Issue by Derpford** [Ri5ux/AliensVsPredator#16]
From what I've seen, the AVP mod assembler and crafting recipes only accept AVP items, even if they're oredicted (i.e., only AVP copper ingots). This is a problem, as I've got a couple mods in my pack that automatically transform items into a single oredicted item, so my players can't actually *get* the AVP ingots. I could deactivate the automatic oredictionary conversions, but that would lead to inventory issues.

**Comment by bvanseg** [comment]
This issue has since been fixed by #273. Closing as completed.
