### ISSUE TITLE
Crash when looking at blastdoor with Waila installed still happens  aliensvspredator-7.0.0.69

### ISSUE THREAD

**Issue by Njet75** [Ri5ux/AliensVsPredator#194]
Game stills crash when looking at blastdoor.
Its clompletly random but its seems that the door is invisible when looking at it.
Then the game crashes.
![Sevastopol door](https://user-images.githubusercontent.com/8996171/227615413-a45b10f3-02d8-44ff-943c-c13580cf9df2.png)
[crash-2023-03-24_19.50.05-client.txt](https://github.com/Ri5ux/AliensVsPredator/files/11065647/crash-2023-03-24_19.50.05-client.txt)

/Michael

**Comment by bvanseg** [comment]
Thanks for the crash report! I will look into fixing this.

**Comment by bvanseg** [comment]
Fixed with #196.
