### ISSUE TITLE
Crash on load IllegalAccessError: tried to access field net.minecraft.block.Block.field

### ISSUE THREAD

**Issue by ProsperCraft** [Ri5ux/AliensVsPredator#21]
https://gist.github.com/ProsperCraft/56ad509e5def250b858acba51c38d81e

**Comment by Ri5ux** [comment]
Has this issue been resolved in newer versions?

**Comment by Ri5ux** [comment]
Assuming this issue is resolved, if it is not, please re-open the issue.
