### ISSUE TITLE
Bed explodes when try to sleep on Varda aliensvspredator-7.0.0.69

### ISSUE THREAD

**Issue by Njet75** [Ri5ux/AliensVsPredator#213]
Dont know if this is avp or some other mod but when trying to sleep on varda the bed explodes.
The cryochamber from Galacricraft works.

/Michael
![vardabed](https://user-images.githubusercontent.com/8996171/227722510-3668d438-982b-4f10-a5db-65527142d070.png)

**Comment by bvanseg** [comment]
Resolved by #219. Closing.
