### ISSUE TITLE
aliensvspredator-7.0.0.70 takes up more block ids

### ISSUE THREAD

**Issue by Njet75** [Ri5ux/AliensVsPredator#224]
I know this is not a bug but the new aliensvspredator-7.0.0.70 takes up more block ids.
Makes it veryhard to use in my modpack.
Is it possible to reduce the block ids ?

/Michael

**Comment by bvanseg** [comment]
Unfortunately no, I suspect this will remain an issue until AVP exists on an MC version later than 1.12.2, as 1.13 is when The Flattening was done (removal of block id limitations). Until then, it is not possible for this issue to be fixed, so will have to close it.

**Comment by Njet75** [comment]
Is there a reason why version 7.0.0.70 uses more block id than version 7.0.0.69 ?

/Michael

**Comment by bvanseg** [comment]
@Njet75 Because more blocks were added (slabs, stairs).

**Comment by bvanseg** [comment]
@Njet75 After researching a little further, you might be able to find a mod that raises the vanilla block ID limit. That might work for your modpack. Hope this helps.
