### ISSUE TITLE
Can't shoot trough grass

### ISSUE THREAD

**Issue by MutanaLuna** [Ri5ux/AliensVsPredator#25]
I'm not able to hurt Mobs by shooting trough grass with weapons.

**Comment by darthvader45** [comment]
I believe this has been fixed.  Use the latest build.

**Comment by ABowlOfSoup** [comment]
Indeed, this has been fixed. However, it remains impossible to target and therefore shoot an entity behind glass pane or leaves. When I get time, I may fix this unless Ri5ux is already on it. Until then, this issue should remain open as a reminder.

**Comment by Ri5ux** [comment]
This is resolved. I am closing this issue. It is also intended to be impossible to shoot entities behind glass panes and leaves. They are solid blocks.
