### ISSUE TITLE
Hives arnt working

### ISSUE THREAD

**Issue by LostGameDev** [Ri5ux/AliensVsPredator#278]
i spawn a queen and drones and nothing happens the drones don't spread resin and the queen's egg sack never grows

**Comment by bvanseg** [comment]
The queen needs a sufficiently large space with no obstructions/walls between her and her egglaying position. She also needs to be in a dark enough space (light level < 7) and have no sky above her. She should also have enough royal jelly to create the ovipositor and also to lay eggs.

**Comment by LostGameDev** [comment]
Thank you! it's been a while since I have used the AVP mod! i must have forgotten about those details
