### ISSUE TITLE
Complaint about the AVP Mod!

### ISSUE THREAD

**Issue by amiryuri** [Ri5ux/AliensVsPredator#289]
This mod could be way better, right now it feels like all it does is adding stuff for the sake of adding stuff, there are no notable gameplay changes.
I am a veteran AVP player (played AVP Classic, AVP2, Predator Concrete Jungle, Hunting Grounds, AVP evolution and AVP 2010), and this mod is a huge letdown for me, I was hoping I could play as a predator (Not playing with their items, but rather playing as an alien or predator character myself, like in AVP games, where you can choose your class and species).
I cannot stab people with my wristblades, I can't cloak, use vision modes (see, Preds usually have heat and xenomorph visions), rip heads and spines off, I am unable to play as an alien either, I should be able to bite mobs, use my tail to strike and impale things, xenos should have their own vision mode as well (see, in AVP 2010 they can psychically see Pheromones, so they can see through walls and their eyes can see in the dark) sprint really fast, both, Preds and Aliens have superhuman strength, they can break walls, dodge bullets and send people flying off with a punch, NONE of which is possible to perform in this mod.
Yeah, I know minecraft has its limitations, I know modding and coding are difficult and all, it's just that efforts are being done towards useless mobs and new items that frankly speaking, are completely useless.
Besides, there have been awesome predator mods before, like Lost Tribes for Skyrim or AJL for AVP2.
I'm certain this project could be so much better if you guys focused on gameplay instead.

**Comment by Njet75** [comment]
You are thinking about this in the wrong way.
Its awesome that bvanseg is updating the mod after several years of no updates.
He is fixing things and why not help him instead of complaining?
