### ISSUE TITLE
Queen stops  laying egg if disturbed aliensvspredator-7.0.0.73

### ISSUE THREAD

**Issue by Njet75** [Ri5ux/AliensVsPredator#295]
Queen stops  laying egg if disturbed aliensvspredator-7.0.0.73
The eggsack never grows back .The room is completly black (Wearing nightvision)
Only solution kill the queen and spawn a new one.

/Michael 

![2023-04-17_21 51 05](https://user-images.githubusercontent.com/8996171/232596913-739a57ad-6450-4ea8-af68-71ccb44a5b1d.png)

**Comment by Njet75** [comment]
Think i solved it.The light level is very sensetive but the eggsack goes thru walls.
![2023-04-17_23 33 44](https://user-images.githubusercontent.com/8996171/232615755-44d9d58e-cb9c-43b0-b277-ad20782a4ae5.png)

**Comment by Njet75** [comment]
Also get this crash after a time has passed,Theres no crashreport only tjis java error code.
Am I using wrong Java version?
[hs_err_pid24260.log](https://github.com/Ri5ux/AliensVsPredator/files/11265305/hs_err_pid24260.log)

**Comment by bvanseg** [comment]
> Also get this crash after a time has passed, there's no crashreport only this java error code. Am I using wrong Java version? [hs_err_pid24260.log](https://github.com/Ri5ux/AliensVsPredator/files/11265305/hs_err_pid24260.log)

This file is not a traditional crash report, it's a dump of what looks to be a snapshot of your machine state at the time of the error/exception. The only part that references AVP is related to the Sevastapol blastdoor model being rendered, and it also appears to be referenced along with `net.malisis.doors`. There may be an incompatibility between AVP and that mod when it comes to the blast doors, but it is unclear.

Could you provide additional context/info about what you were doing at the time that the error occurred?

**Comment by bvanseg** [comment]
> Think i solved it.The light level is very sensetive but the eggsack goes thru walls sometime. Also using the glass from avp helps with light level. It´s workig but a little bit buggy. ![2023-04-17_23 33 44](https://user-images.githubusercontent.com/8996171/232615755-44d9d58e-cb9c-43b0-b277-ad20782a4ae5.png)

The eggsack clipping walls still is a known issue, it will be fixed soon.

**Comment by Njet75** [comment]
The crash between Sevastopol door and Malisis doors make sense.
I have setup 3 testdoors outside my base and was moving towards them.I also got several malisis doors inside the base.
![blastdoor2](https://user-images.githubusercontent.com/8996171/232882057-ec21d07f-d1f4-4438-af5b-d5bf18247fe1.jpg)

**Comment by Njet75** [comment]
Seems to work whit Sevastopol doors removed

**Comment by bvanseg** [comment]
> Seems to work whith Sevastopol doors removed

Interesting, I will take a look at it, then. Thanks for bringing the bug to my attention!

**Comment by Njet75** [comment]
I had by mistake unfortunately installed foamfix in my modpack. I'm testing without it and so far no crash.

**Comment by Njet75** [comment]
Closing this issue.
The crash was related to foamfix.
The only issue remaining is eggsack clipping thru walls.
If you feed queen with royal jelly she begins laying egg again.
