### ISSUE TITLE
Rendering Problems 

### ISSUE THREAD

**Issue by DerMax93** [Ri5ux/AliensVsPredator#3]
When Items from the AvP mod are rendered in one's inventory they influence the way the other items in the inventory are rendered. Some Items do break completely (![screenshot_20181002_210712](https://user-images.githubusercontent.com/1215016/46370899-2943e480-c687-11e8-8318-70ee1d2981ef.png)). Other items only get weird-shadows. The first screenshot is from my "personal" modpack where I just added AvP (+mdxlib) to FTB:Revelations. 
Knowing that it could be an interaction between other mods I built a second instance with only AvP (+mdxlib) added to a fresh vanilla instance. Even there the same weird shadows appeared ( ![screenshot_20181002_210855](https://user-images.githubusercontent.com/1215016/46370981-660fdb80-c687-11e8-85b8-e641a24df338.png)
). None of the vanilla items are breaking completely, but it does appear the rendering is still influenced.

Versions (from the 2nd Screenshot):
MC: 1.12.2
Forge: 14.23.4.2705
AvP: 6.0.0.9
MDXLib: 3.0.0.5

While the setup I am running is quite niche (Linux), my friend who runs Windows 10 is having the same symptoms.

**Comment by darthvader45** [comment]
This is indeed a bit annoying, and deals with how AvP renders its own items.  Apparently, there is no compat between vanilla and AvP rendering code, which may need to be dealt with.

**Comment by sadface-0** [comment]
I am also experiencing this issue.

**Comment by bvanseg** [comment]
@DerMax93 @darthvader45 @mr-poyo This issue was with MDXLib itself and https://github.com/Ri5ux/MDXLib/pull/4 fixes it.
