### ISSUE TITLE
Acid Pool causes crashing

### ISSUE THREAD

**Issue by UnoriginalUmbrella** [Ri5ux/AliensVsPredator#30]
Apparently at random points, while exploring, my game causes crashes. I then looked at my crash reports and found out that the "Acid Pool" is causing the crashes. Could you please fix this? 
-- Entity being ticked --
Details:
	Entity Type: avp:acidpool (org.avp.entities.EntityAcidPool)
	Entity ID: 34733
	Entity Name: entity.AcidPool.name
	Entity's Exact location: -118.47, 10.33, -60.47
	Entity's Block location: World: (-119,10,-61), Chunk: (at 9,0,3 in -8,-4; contains blocks -128,0,-64 to -113,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

**Comment by bvanseg** [comment]
This was fixed as of PR #29, requesting this be closed.

@UnoriginalUmbrella (and anyone else looking to make bug reports for AvP) please use the official bug tracker at https://aliensvspredator.org/ at the request of Ri5ux. Thanks!
