### ISSUE TITLE
Hive Chunk Loading Issues (potentially)

### ISSUE THREAD

**Issue by voidswrath** [Ri5ux/AliensVsPredator#31]
I had added the AVP mod into one of my modpacks and servers. We have been seeing some very strange issues for the past weeks since adding it. They involved chunks taking a very long time to load and could potentially time out the server. We also noticed there was around 3-10 minutes of lag on the server before you caught up to real time. Strange issues and I pin pointed it back to when we added the AVP mod. I made some config changes that made the hive not generate and as soon as that was implemented those significant issues went away. I don't have a direct issue with the mod, but I think some issues may be attached to how you are generating these hives (especially if you have multiple dimension mods in your modpack).

Sorry for not having a direct post with concrete info to show. I can just tell from my experience it seems there is something going on with the avp mod and the modpack I have here.

Versions being used:
[1.7.10-10.13.4.1614-1.7.10][1.0.0.70] mdxlib
[1.7.10-10.13.4.1614-1.7.10][4.0.0.817] aliensvspredator

**Comment by Ri5ux** [comment]
We no longer develop on version 1.7.10. Please update to the 1.10.2 release of AliensVsPredator.
