### ISSUE TITLE
aliens are not spawning in my world[mc 1.12.2]

### ISSUE THREAD

**Issue by Bacurin42** [Ri5ux/AliensVsPredator#333]
I'm trying to play this mode in survival, but it's not spawning aliens or predators or eats, I don't know if this is a bug. I hope the admin team responds to me [mc 1.12.2] [avp 7.0.0.74] [mdx 4.0.0.35]

**Comment by bvanseg** [comment]
There is a new config file, you may need to re-enable auto/overworld spawns in it. check under config/avp/config.json!
