### ISSUE TITLE
Game fails to start (crash) when I try to edit the config file

### ISSUE THREAD

**Issue by SpencerMeow** [Ri5ux/AliensVsPredator#34]
Im trying to edit the alien spawn biomes to work with Biomes O Plenty, making sure I use all the right prefixes and stuff, but the game fails to start when I do it, vanillafix says it is mdx lib and/or avp, and im not sure how to fix it.

**Comment by bvanseg** [comment]
No crash report provided, so will not fix. If this crash still occurs for you, please feel free to create a new issue with the relevant crash report attached. Thanks!
