### ISSUE TITLE
Bats out of hell

### ISSUE THREAD

**Issue by Liloletinyme** [Ri5ux/AliensVsPredator#34]
When setting up an artificial huge underground, it's almost impossible to keep the bats from spawning (at least without an obnoxious amount of lights, which ruin the atmosphere). This leads to a hive full of chiropteramorphs, which don't seem to spread the resin.  The best solution I've thought of (outside other mods like torchmaster), was the turrets, but the bats are either too small or too fast for them to hit.   The chiropteramorphs also seem to kill other mobs before the facehuggers can impregnate them.  Would it be too troublesome to have chiropteramorphs spread the resin? Or have some way to keep facehuggers from going after bats?  (This should probably be another request, but it's revelent, based on the resin spread, the drones know when a queen is near, can they ignore passive mobs for the face huggers to impregnate when a queen is near? Or at least slow down?)

**Comment by Ri5ux** [comment]
I won't have the chiropteramorphs place resin or prevent facehuggers from going after bats, as that defeats the purpose of a facehugger, but I could possibly look at making the turrets hit the bats properly if that's alright with you.

**Comment by Liloletinyme** [comment]
That would work out great! Thank you.  The only other problem is the xenomorphs killing mobs before facehuggers can reach them, but I've worked around it with some effort, and I can see the difficulty in getting the xenos to recognize a mob is being targeted by a facehugger.  Thank you for this mod! I've been starved for some avp and this brought me back to minecraft.
