### ISSUE TITLE
My game crashed before it started

### ISSUE THREAD

**Issue by Caique00** [Ri5ux/AliensVsPredator#35]
this was the crash mesage

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AliensVsPredator (avp)

**Comment by bvanseg** [comment]
This exception doesn't say much other than the mod crashed during loading. We'll need a crash log file to really see why it crashed.

**Comment by bvanseg** [comment]
If this crash still occurs for you on the latest version, please feel free to create a new issue. Closing.
