### ISSUE TITLE
/playermode

### ISSUE THREAD

**Issue by Xorgadget** [Ri5ux/AliensVsPredator#4]
Hello,

The /playermode command is being bypassed by AI.

Details: 

if set to 3 drones and other aliens still attack the player.

if set to 2, predators attack the player without consideration to the variable as well.

Versions:

AMDXLIB 1.0.0.10
AVP 4.0.0.567
Minecraft Forge 10.13.4.1614

Notes:
This command worked in a previous update. (unknown)
The playermode resets upon logging out and logging on in singleplayer

Video on steps to reproduce:
https://drive.google.com/open?id=0B-wcmEkV6So2VS1WV2F0X3lzMkU

Suspicions:
I think this problem is to do with this file.

https://github.com/Ri5ux/AliensVsPredator/blob/master/src/main/java/org/avp/PlayerModeHandler.java

edit: I am also tagging Riux on this. @Ri5ux

**Comment by Ri5ux** [comment]
Hi, as of now, player modes are still highly in development, so the problems you are experiencing are normal. I will leave this issue open as a reminder to continue developing them.

**Comment by Xorgadget** [comment]
Thanks. ;)

**Comment by Xorgadget** [comment]
Any progress so far?

**Comment by darthvader45** [comment]
Seems the player modes will be moved to a separate mod, @Xorgadget.  However, the mod is doing great.  The only big problem for Ri is finishing the shaped blocks.  Had to use his own rendering methods to make sure they render correctly and also work like they're supposed to.

**Comment by Xorgadget** [comment]
Nice i'd love to see where this mod goes.
I suppose I can close this issue then?

**Comment by darthvader45** [comment]
Yep.
