### ISSUE TITLE
DIM IDS

### ISSUE THREAD

**Issue by MR-Spagetty** [Ri5ux/AliensVsPredator#40]
What are the dim ids of the dimensions added by this mod and why isnt there a config option to change them.

**Comment by SeriousTIEM** [comment]
This is seconded.

**Comment by Njet75** [comment]
The dim ids are 2 and 3 if you want to dimmap in Advanced Rockerty.

/Michael
![dimids](https://user-images.githubusercontent.com/8996171/209876684-9283be0f-46ec-431b-bd72-b3064ea03c15.JPG)

**Comment by bvanseg** [comment]
#142 now allows for modifying dimension IDs and will be merged into the next release.
