### ISSUE TITLE
The Medpod create some entities which can not kill by player.

### ISSUE THREAD

**Issue by SIZStan** [Ri5ux/AliensVsPredator#42]
https://user-images.githubusercontent.com/37479377/103264673-60c8a500-49e6-11eb-92ef-6158e4a0ba1c.mp4

When I turn on the hitbox. I can see the entity, but I can not kill them by hit.It can be kill only by command.

**Comment by SIZStan** [comment]
![image](https://user-images.githubusercontent.com/37479377/103264814-c583ff80-49e6-11eb-8fd1-3416e227ca6e.png)

**Comment by bvanseg** [comment]
The entity's existence intentional. The entity you are seeing is meant to act as a mounting point for entities to mount the medpod tile entity. However, that entity persisting when the medpod is destroyed isn't intentional. Marking as a bug.

**Comment by bvanseg** [comment]
Resolved by #138. Closing.
