### ISSUE TITLE
The Turret make some error and lag in client.

### ISSUE THREAD

**Issue by SIZStan** [Ri5ux/AliensVsPredator#43]
https://paste.ubuntu.com/p/YPHJSJs942/

When place the Turret on the floor my client`s log will show this error and get lag.

**Comment by bvanseg** [comment]
The paste you posted requires a login. Would you mind posting a public paste, if possible? Thanks.

**Comment by bvanseg** [comment]
It's still not clear what the issues you were facing with the turret were, however, #74 adds a lot of fixes and improvements for turrets. This issue should be closed when that PR is merged in.

**Comment by bvanseg** [comment]
The turret optimizations have since been merged, and the issue poster has not followed up, so this can be closed. @SIZStan if you encounter any further lag with the turret, please feel free to open up a new issue. Thanks!
