### ISSUE TITLE
Game nearly crashes while loading 3D Models in inventory

### ISSUE THREAD

**Issue by Bastelking** [Ri5ux/AliensVsPredator#47]
When i open one of the AVP tabs, it nearly crashe because it has to deal with all the 3d Models at once. Please add 2D Models instead and spawneggs for  the enteties.

**Comment by Vetpetmon** [comment]
This is a hardware issue, please include details about your computer specs. Normal PCs have no trouble with rendering the creative tabs.

**Comment by bvanseg** [comment]
I can't reproduce this issue, and given that it has been up for 2 years, I'm considering it closed. If you're still encountering any lag with items in the inventory, feel free to open up a new issue detailing what items, in what creative tab, etc.
