### ISSUE TITLE
Crashes after 15 min of gameplay.

### ISSUE THREAD

**Issue by aml50** [Ri5ux/AliensVsPredator#49]
[](url)
[crash-2021-03-17_16.15.24-server.txt](https://github.com/Ri5ux/AliensVsPredator/files/6159495/crash-2021-03-17_16.15.24-server.txt)

The game seems to crash after about 15 min and the crash log always mentions Entity Ticks and Chestbursters.
I'm playing on a personal modpack in CurseForge.

**Comment by aml50** [comment]
After some testing with a second mod pack using the same mods and playing around with the alien life cycle in creative, I didn't run into the same issue. But after loading up my original save, the same issue keeps popping up. Since the crash report mentions chestbursters, I did a test in the same save world in creative. I spawned a chestburster, a face hugger, impregnated a villager, watch a burster come from it. None of those had any issue. But after waiting about 5-15 minutes for it to grow into a xeno, the same crash happened. It seems that, on this save at least, that the game crashes when chestbursters grow into xenos.

**Comment by Susyguy6078** [comment]
Idk man but it doesn't crash on mine it only crash if I had ScapeandRun parasite mod

**Comment by Vetpetmon** [comment]
This is a compatibility issue with Scape and Run Parasites, the first error in the stacktrace is this:
`com.dhanantry.scapeandrunparasites.util.handlers.EventHandler.onEntityJoinWorld`

The super class for `onUpdate()` is causing issues. Unfortunately, because SRP is not open source, there's nothing anyone can do.

**Comment by bvanseg** [comment]
As @Vetpetmon, this seems to be a SRP issue and not an AVP issue. It is up to them to fix it. Closing.
