### ISSUE TITLE
Duplicate ID Error

### ISSUE THREAD

**Issue by Gamerbolts** [Ri5ux/AliensVsPredator#5]
Hello I am trying to add this mod to my mod pack of about 275 mods. When I added your mod I am getting a duplicate ID error. I am confused because I thought with the newer versions of MC that wasn't supposed to be a thing. 

Here is my error log http://pastebin.com/SMpE1iTZ

Any help is appreciated. Thank you!

**Comment by Xorgadget** [comment]
java.lang.IllegalArgumentException: Duplicate id: tileEntitySolarPanel

Duplicate id: tileEntitySolarPanel <--- this tells me it's a solar panel.

Ok, well try to:
- [ ] Remove some mods with solar panels. Like: industrialcraft-2-2.2.822-experimental.jar

**Comment by Gamerbolts** [comment]
Hi thanks for the reply. I thought it was your mod but apparently it was Solar Expansion not playing right. I took that out and was able to load up my modpack. Thanks for the help!
