### ISSUE TITLE
AVP lags world

### ISSUE THREAD

**Issue by MrVaiza** [Ri5ux/AliensVsPredator#53]
after playing for five minutes loading the world it stats to stutter periodically more like a freeze actually this has happened every time i add this mod to my wrold and idk why the world just stutters idk if its cuz of a mod or what but its only this mod every time i download it this really sucks cuz i can never play with this awesome mod

**Comment by bvanseg** [comment]
This issue is too broad. The mod is being reworked recently, so it is expected that this lag will disappear over time. Closing.
