### ISSUE TITLE
Aliens disappear when spawned

### ISSUE THREAD

**Issue by MightyGamersMx** [Ri5ux/AliensVsPredator#54]
Whenever i spawn a alien, it just disappears out of nowhere.

**Comment by bvanseg** [comment]
@MightyGamersMx A bit late to this issue, but if aliens are still instantly de-spawning for you, double-check that your difficulty is not set to peaceful. If you're not in peaceful difficulty, please provide the game log that was created during the time you experienced this issue.

**Comment by bvanseg** [comment]
Can not reproduce this issue. Closing.
