### ISSUE TITLE
Does not work server side. Crashes when run on server

### ISSUE THREAD

**Issue by TheGhostNarwhal** [Ri5ux/AliensVsPredator#56]
When attempting to use the mod server side it gives this crash report: 
[crash-2023-01-03_21.41.06-server.txt](https://github.com/Ri5ux/AliensVsPredator/files/10341456/crash-2023-01-03_21.41.06-server.txt)

**Comment by Rsslone** [comment]
+1
On a sponge env, idk if Narwhal is.

**Comment by bvanseg** [comment]
PR #68 fixes this issue.

**Comment by bvanseg** [comment]
Resolved by #68. Closing.
