### ISSUE TITLE
How do I get to the two dimensions?

### ISSUE THREAD

**Issue by Gamerbolts** [Ri5ux/AliensVsPredator#7]
I was messing around with the mod and see there are two portals but can't tell how you get to the dimensions other than creative. Is there any way?

**Comment by Gamerbolts** [comment]
Also going to the dimensions in creative, when I try to exit the the dimension and go back to the overworld I spawn about 200m in the air and fall down. around 500m from where I put the portal. Is there any fix to this? I want to add this in my modpack, but without being in creative that would surely kill whoever falls from the portal.

**Comment by Ri5ux** [comment]
They are creative mode only dimensions until said otherwise.

**Comment by Gamerbolts** [comment]
I've noticed a lot of new updates for AVP. Has one of these made it to where you could get to the dimensions in survival? or is it still creative only.

**Comment by Ri5ux** [comment]
Soon they will be able to be accessed in survival mode. By soon I mean a few months.
