### ISSUE TITLE
Missing Mobs(question)

### ISSUE THREAD

**Issue by PhantomCrafter868** [Ri5ux/AliensVsPredator#70]
i wanted to know why some creatures like dracomorph,panteramorph,boiler,etc appear in the game files with textures and .class files but dont appear in game as spawn eggs,even with /summon command they dont spawn. Are they not added yet or its a bug?

**Comment by bvanseg** [comment]
@PhantomCrafter868 The mobs you are asking about appear to have not been fully implemented into the game yet based on the code, so it seems intended and not a bug.
