### ISSUE TITLE
/avpsettings and incorrect privilages

### ISSUE THREAD

**Issue by Xorgadget** [Ri5ux/AliensVsPredator#8]
Hello, @Ri5ux 

I have found an issue with the /avpsettings command.

The command requires admin privaleges to be used.

![image](https://cloud.githubusercontent.com/assets/20858676/18277743/d079260c-744f-11e6-9477-353eca7d9770.png)

Best wishes, 
-Ruben

**Comment by Ri5ux** [comment]
Thanks, I'll get this fixed!

**Comment by Ri5ux** [comment]
This is now resolved.

**Comment by Xorgadget** [comment]
Excellent.
