### ISSUE TITLE
casillero multiplica objetos y recetas muy dificiles 

### ISSUE THREAD

**Issue by andrunetito** [Ri5ux/AliensVsPredator#8]
version 1.12.2 last version mod , 
When placing objects in the central slots of the lockers (normal weapons and lockers) and clicking with the left button on them, multiply the items by many, the resources are difficult to obtain and the recipes are too demanding according to the material they require. . would help to put structures like ships or temples to get some things in them, pd I love your creation

**Comment by bvanseg** [comment]
Unable to reproduce this issue. If it still occurs, please feel free to create a new issue, preferably with a video of the bug.
