### ISSUE TITLE
problem texture

### ISSUE THREAD

**Issue by gabrielgamercv** [Ri5ux/AliensVsPredator#9]
hello ri5ux has a problem in xenomorph texture looks to print !

(https://cloud.githubusercontent.com/assets/22416677/18809695/f1482db2-820d-11e6-9004-58b7a81308a2.png)

**Comment by Ri5ux** [comment]
The mod is not at fault. Your graphics processor is either too old, or your drivers are not up-to-date. Please update your graphics drivers or switch to a system with a newer graphics processor.
